### ISSUE TITLE
Error using qemu with the Ubuntu build/img

### ISSUE THREAD

**Issue by cdbattags** [iximiuz/docker-to-linux#12]
First off, just want to say what you're doing with this is absolutely amazing!

Steps to reproduce:

```
make ubuntu

qemu-system-x86_64 -drive file=linux.img,index=0,media=disk,format=raw -m 4096
```

See image for the error:

<img width="741" alt="Screen Shot 2021-05-05 at 22 12 05" src="https://user-images.githubusercontent.com/4399055/117232426-12da0880-adef-11eb-99be-e23a9dd218fc.png">

**Comment by iximiuz** [comment]
Thanks for the good words!

Ubuntu not loading is a regression after the recent distr version bump. Seems like Ubuntu folks changed the default path to `vmlinuz` and `initrd` files from just `/` to `/boot`. I [adjusted the syslinux config](https://github.com/iximiuz/docker-to-linux/commit/95b261117bcbebb88507277eefa70f5c9e2b59c3). Thanks for reporting!

**Comment by iximiuz** [comment]
Resolved with https://github.com/iximiuz/docker-to-linux/commit/95b261117bcbebb88507277eefa70f5c9e2b59c3.
