### ISSUE TITLE
[Question] Scratch images

### ISSUE THREAD

**Issue by Zekfad** [iximiuz/docker-to-linux#13]
Hi, this project looks great, and I'm curious if it's possible to run scratch images same way?
Let's say pure c printf to terminal and infinity loop, or just a standalone web server with all required dependencies included, excluding systemd and other unnecessary parts?

**Comment by iximiuz** [comment]
Hi Yaroslav! I think what you're asking for is technically doable. All you need is to bundle the kernel binary with your application binary (assuming all the dependencies are statically linked). Then pack it into a thin image and boot from it. However, this particular project wouldn't be helpful given its current functionality. It relies heavily on the standard distr tools to bring in the kernel binary. And you need rather an inverse tool.

**Comment by Zekfad** [comment]
Thanks for your reply! Do you have any suggestions where can I get more related information?

**Comment by iximiuz** [comment]
I haven't made much research yet, but here are some items from my list that you may find interesting:

- https://github.com/combust-labs/firebuild
- https://github.com/unikraft/unikraft
- https://github.com/containers/krunvm
- https://github.com/nanovms/ops
- https://twitter.com/egernst/status/1389683002150584323
