### ISSUE TITLE
Ext4 please

### ISSUE THREAD

**Issue by suntong** [iximiuz/docker-to-linux#15]
Would you make this `ext4` please?

https://github.com/iximiuz/docker-to-linux/blob/94ccfe3ef1257d31c8046fcbe08e0067972d16e8/create_image.sh#L17

I think Debian choosing `ext4` over `ext3` says a lot about its advantages. 
Please consider. thx

**Comment by iximiuz** [comment]
Oh, indeed. Not sure why I decided to use `ext3` in the first place. Probably just some mindless copy/paste. [Fixed](https://github.com/iximiuz/docker-to-linux/commit/1aa7ada6f6cb909599550baff8c4228c061528aa).
