### ISSUE TITLE
Practical use

### ISSUE THREAD

**Issue by suntong** [iximiuz/docker-to-linux#16]
Hi Ivan, 

I don't use tweeter, so let me put my practical use-case here.

I've been looking for such docker-to-linux solution for years, and I'll search for it every now and there, but only yesterday did I find your project in google. I think your project, after being existing for two years, is taking mainstream and is becoming top hits from google.

Congratulations!

> If you’re aware of the real use of the docker-to-linux project, please drop me a message and share your experience.

For me, I'll be using it to automate my Debian system installation. It's only for my personal use, which varies dramatically from the massive system installation that enterprises use (like Vagrant etc), as I have my specific ways of doing things, like alias that I'be been using for decades. Not being able to get into my accustomed environment in a brand new machine is the "dark age" to me, and I need to get over that period as short as possible.

However, there aren't many ready-made solutions that has both the power and versatility that allows me to do that, as far as real HD is concerned. I.e, 

- For VM, I use Debian Preseed installation 
- For Docker, I use `packer`

But for real HD installation, when it is only a bare-metal that I have to install everything from scratch, that's truly a dark age to me, that's why I've been looking for such docker-to-linux solution for years. 

Thanks!

**Comment by suntong** [comment]
> I have my specific ways of doing things

Just for one example, I make and use my own DNS, DHCP, local caching and ads filtering server for my LAN (using [`dbab`](https://github.com/suntong/dbab/)). I have automated the [whole building process for the DNS, DHCP, local caching and ads filtering server via packer](https://github.com/suntong/dbab-packer/tree/master/build-dbab) as docker image. It'll be cool to make the last step to put it in a real bare-metal machine, removing the dependency on docker to run it.

**Comment by iximiuz** [comment]
Hi @suntong! Thank you very much for your feedback! And for the issues you opened. It makes a lot of sense to me. I need some time to digest it and to understand what would be doable with my tight time budget. I'll get back to you as soon as I can!
