### ISSUE TITLE
Create Multiple Partitions

### ISSUE THREAD

**Issue by redxking** [iximiuz/docker-to-linux#22]
Is there a way to make multiple partitions? I'd like to break up the drive into three different partitions

**Comment by iximiuz** [comment]
Hi! While, theoretically, it's doable, I don't see a good fit for such functionality in docker-to-linux. The project was meant to accompany a blog post and serve solely an educational purpose. I'd like to keep it as simple as only possible to illustrate the main idea - converting a container into a VM image.
